sudo: required
language: node_js
node_js:
  - '8'
cache: yarn
before_install:
  - sudo /etc/init.d/postgresql stop
  - openssl aes-256-cbc -K $encrypted_1f8d325dded8_key -iv $encrypted_1f8d325dded8_iv -in secrets.tar.enc -out secrets.tar -d
  - tar xvf secrets.tar
services:
  - docker

stages:
  - test
  - publish
  
jobs:
  include:
    - stage: test
      script: docker/test
    - stage: publish
      script:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - cd cg
        - make release
        - cd ..
        - cd api
        - make release
        - cd ..
        - cd frontend
        - make release