const VALID_RUN_MODES = {
  PROCESSOR: 'PROCESSOR',
  CONTROLLER: 'CONTROLLER'
};

const RECTIFICATION_STATUSES = {
  PENDING: 'PENDING',
  DISAPPROVED: 'DISAPPROVED',
  APPROVED: 'APPROVED'
};

const DATA_STATUSES = {
  UNCONSENTED: 'UNCONSENTED',
  CONSENTED: 'CONSENTED',
  ERASED: 'ERASED'
};

module.exports = {
  VALID_RUN_MODES,
  RECTIFICATION_STATUSES,
  DATA_STATUSES
};
