const VALID_RUN_MODES = {
  PROCESSOR: 'PROCESSOR',
  CONTROLLER: 'CONTROLLER'
};

const RECTIFICATION_STATUSES = {
  PENDING: 'PENDING',
  DISAPPROVED: 'DISAPPROVED',
  APPROVED: 'APPROVED'
};

module.exports = {
  VALID_RUN_MODES,
  RECTIFICATION_STATUSES
};
